Book/urls.py
from django.urls import path
from .views import IndexView, BookDetailView, GenreView, AddBookView, BookUpdateView, BookDeleteView

app_name ='Book'

urlpatterns = [
    path('', IndexView.as_view(), name='ex2'),
    path('add/', AddBookView.as_view(), name='add'),
    path('g/<str:genre>', GenreView.as_view(), name='genre'),
    path('<slug:slug>/', BookDetailView.as_view(), name='book-detail'),
    path('<slug:slug>/edit', BookUpdateView.as_view(), name='edit-detail'),
    path('<slug:slug>/delete', BookDeleteView.as_view(), name='delete-detail'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tim.urls', namespace='tim')),
    path('books/', include('Book.urls', namespace="Book")),
    
]

tim/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from tim.views import Ex2View, PostPreLoadTaskView, SinglePostView

app_name = 'website'

urlpatterns =[
    path('ex1', TemplateView.as_view(template_name="ex1.html", extra_context={'title': 'Custom Title', 'number': '24'})),
    path('ex2', Ex2View.as_view(), name='ex2'),
    path('rdt', RedirectView.as_view(url='http://youtube.com/veryacademy'), name='go-to-very'),
    path('ex3/<int:pk>/', PostPreLoadTaskView.as_view(), name='redirect-task'),
    path('ex4/<int:pk>/', SinglePostView.as_view(), name='singlepost'),
]

Book/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Books(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.IntegerField()
    count = models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)    

tim/models.py
from django.db import models

class Post(models.Model):
    name = models.CharField(max_length=200)
    count = models.IntegerField(null=True)

    

       

Book/forms.py
from django import forms
from .models import Books

class AddForm(forms.ModelForm):

    class Meta:
        model = Books
        fields = ('title', 'genre', 'author', 'isbn')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'genre': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control'}),
        }

Book/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from Book.forms import AddForm
from Book.models import Books
from django.db.models import F
from django.utils import timezone

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.shortcuts import redirect

class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if (not self.request.user.is_authenticated):
            return redirect_to_login(self.request.get_full_path(),
                                    self.get_login_url(), self.get_redirect_field_name())
        if not self.has_permission():
            return redirect('/books')            
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)                    


class BookDeleteView(DeleteView):

    model = Books
    template_name = 'delete.html'
    context_object_name = 'book'
    success_url = '/books/'

    



class BookUpdateView(UserAccessMixin, UpdateView):
    raise_exception = False
    permission_required = 'Book.change_books'
    permission_denied_message = ""
    login_url = '/books/'
    redirect_field_name = 'next'

    model = Books
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/books/'

"""
class AddBookView(FormView):
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/books/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
"""       
class AddBookView(CreateView):
    model = Books
    template_name = 'add.html'
    form_class = AddForm
    success_url = '/books/'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['title'] = 'Enter Title'
        initial['genre'] = 'Enter Genre'
        return initial


"""
class IndexView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Books.objects.all()
        return context
"""

class IndexView(ListView):
    model = Books
    template_name = "home.html"
    context_object_name = 'books'
    paginate_by = 2

    #def get_queryset(self):
        #return Books.objects.all()[:3]


class GenreView(ListView):
    model = Books
    template_name = 'home.html'
    context_object_name = 'books'
    paginate_by = 1

    def get_queryset(self, *args, **kwargs):
        return Books.objects.filter(genre__icontains=self.kwargs.get('genre'))



class BookDetailView(DetailView):

    model = Books
    template_name = 'book-detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Books.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count') + 1)

        context['time'] = timezone.now()

        return context
    
    

tim/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic.base import TemplateView, RedirectView
from tim.models import Post
from django.db.models import F


class Ex2View(TemplateView):

    template_name = "ex2.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.get(id=1)
        context['data'] = "Context Data for Ex2"
        return context

class PostPreLoadTaskView(RedirectView):

    pattern_name = 'tim:singlepost'
    
    def get_redirect_url(self, *args, **kwargs):

        post = Post.objects.filter(pk=kwargs['pk'])
        post.update(count=F('count') + 1)

        return super().get_redirect_url(*args, **kwargs)


class SinglePostView(TemplateView):
    template_name = "ex4.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return context

Book/templates/add.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="max-width: 600px;">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful books to help you know the nature of life</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Book/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
         integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to books {% endblock %}</title>     
</head>
<body>
     {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
         integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEW1d1vI9IOYy5n3zV9zzTtmI3UKsdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
         integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCEx13Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

Book/templates/book-detail.html
{% extends "base.html" %}
{% block content %}
<style>
div i {
    position: absolute;
    top: 80px;
    right: 700px;
    /* border: 1px solid; */
    border-radius: 50%;
    /* padding: 11px; */
    height: 30px;
    width: 30px;
    display: flex !important;
    align-items: center;
    justify-content: center;
    background-color: white;
    color: cornflowerblue;
    box-shadow: 0 0 8px 3px #B8B8B8;
  }
div p {
    position: absolute;
    top: 80px;
    right: 600px;
}  
</style> 
<link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet" />
<div>
 <a href="{% url 'Book:edit-detail' slug=book.slug %}"><i class="fa fa-edit"></i></a>
 
</div> 

<div class="container" style="max-width: 800px;">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div>
        <h1 class="display-4">{{book.title}}</h1>
        <p><button> <a href="{% url 'Book:delete-detail' slug=book.slug %}">Delete</a></button></p>
        </div>
        
        <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">{{book.genre}}</small>
            <small class="text-muted">{{book.isbn}}</small>
            <small class="text-muted">{{time}}</small>
        </div>
    </div>
</div>
{% endblock %}

Book/templates/delete.html
{% extends 'base.html' %}

{% block content %}


<p>Are you sure you want to delete "{{book}}"?</p>
<form method="post">
    {% csrf_token %}
    <a href="{% url 'Book:book-detail' slug=book.slug %}">cancel</a>
    <input type="submit">
</form>

{% endblock %}

Book/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful story books to help you know the nature of life.</p>

    </div>
    <div class="py-5">
        <div class="row">
            {% for book in books %}
            <div class="col-md-4">
                <a class="text-dark" href="{% url 'Book:book-detail' slug=book.slug %}">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold;min-height: 42px;">
                             {{book.title|truncatechars:50}}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{book.genre}}</small>
                                <small class="text-muted">{{book.isbn}}</small>
                            </div> 
                            
                        </div>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Book/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="navbar-nav">
        <a class="nav-link active" href="{% url 'Book:ex2' %}">Books</a>
        </li>
        <li class="navbar-nav">
        <a class="nav-link" href="{% url 'Book:add' %}">Create Book</a>
        </li>
        
      </ul>
    </div>
</nav>

tim/templates/ex1.html
// Homepage
<hr>
{{title}}
<br>
{{number}}

tim/templates/ex2.html
//TemplateView within view.py
<hr>
<a href="{% url 'tim:go-to-very' %}">very</a>
<hr>
{{data}}
<hr>
{{posts.name}}
<hr>
<a href="{% url 'tim:redirect-task' pk=posts.id %}">{{posts.name}}</a>

tim/templates/ex4.html
// Show single page
<hr>
{{posts.name}}